-- Curated Codenames boards for human operative mode: 25 words + key + predetermined first blue clue (2–4 words).
-- Run in Supabase SQL Editor after 001, or use `supabase db push` if you use the CLI.
-- Server reads with SUPABASE_URL + SUPABASE_ANON_KEY (or service role); anon needs SELECT.

create table if not exists public.codenames_curated_puzzles (
  id smallserial primary key,
  words jsonb not null,
  assignment jsonb not null,
  first_clue text not null,
  first_clue_number smallint not null check (first_clue_number between 2 and 4),
  first_clue_target_indices jsonb not null
);

comment on table public.codenames_curated_puzzles is 'Preset Codenames grids; operative games pick one at random. First blue clue is fixed; later clues use Gemini.';

alter table public.codenames_curated_puzzles enable row level security;

create policy "codenames_curated_select_public"
  on public.codenames_curated_puzzles for select
  to anon, authenticated
  using (true);

INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["FISH","BEACH","WAVE","WATER","POOL","PORT","SHIP","SUB","WHALE","MOON","NIGHT","FIRE","ROCK","MOUNT","FIELD","GRASS","KING","QUEEN","CROWN","KNIGHT","PLANE","CAR","BRIDGE","WALL","POISON"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'OCEAN', 3, '[0,1,2]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["BAND","PITCH","NOTE","JAM","PIANO","OPERA","FLUTE","HORN","ORGAN","DOCTOR","NURSE","HOSPITAL","DISEASE","CHEST","HEART","HEAD","FACE","ARM","TABLE","CHAIR","BED","KEY","LOCK","ROCK","POISON"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'SOUND', 4, '[0,1,2,3]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["FRANCE","GERMANY","GREECE","ENGLAND","AMERICA","CANADA","MEXICO","CHINA","INDIA","EGYPT","ROME","LONDON","BEIJING","TOKYO","MOSCOW","AFRICA","EUROPE","ALPS","AMAZON","ATLANTIS","BERLIN","MAPLE","ICE","GLASS","DEATH"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'NATION', 3, '[0,1,2]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["APPLE","ORANGE","HONEY","JAM","BERRY","CHOCOLATE","COOK","LEMON","PIE","HAM","PLATE","FORK","KNIFE","GLASS","MUG","BOTTLE","PAN","CARROT","FIRE","WATER","FIELD","GRASS","ROOT","LOG","POISON"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'SWEET', 4, '[0,1,2,3]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["BEAR","DOG","HORSE","RABBIT","CAT","WHALE","SHARK","EAGLE","WORM","SPIDER","BUG","FLY","BAT","MOUSE","DUCK","KANGAROO","LION","PENGUIN","TABLE","CHAIR","BED","KEY","LOCK","BANK","DEATH"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'PET', 3, '[0,1,2]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["IRON","COPPER","GOLD","NAIL","BOLT","NUT","DIAMOND","IVORY","LEAD","PAPER","GLASS","PLASTIC","COTTON","CLOUD","DROP","WIND","SNOW","ICE","FIRE","LASER","TORCH","MATCH","LIGHT","DAY","BOMB"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'METAL', 2, '[0,1]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["ICE","SNOW","COLD","ICICLE","WIND","CLOUD","WATER","WAVE","STREAM","FIRE","LIGHT","LASER","TORCH","DRAGON","PHOENIX","STAR","MATCH","TICK","HORSE","DOG","CAT","TABLE","CHAIR","BED","DEATH"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'FREEZE', 2, '[0,1]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["KING","QUEEN","CROWN","KNIGHT","PRINCESS","RULER","GOLD","IVORY","RING","SOLDIER","PISTOL","MISSILE","BOMB","WAR","SHIP","PLANE","TRAIN","JET","FIELD","GRASS","MOUNT","TOWER","WALL","BRIDGE","POISON"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'ROYAL', 3, '[0,1,2]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["MOON","STAR","SATURN","JUPITER","MERCURY","ALIEN","TELESCOPE","SATELLITE","LASER","TRAIN","CAR","SHIP","PLANE","HELICOPTER","PILOT","ENGINE","JET","SUB","HOTEL","BED","TABLE","CHAIR","KEY","LOCK","DEATH"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'ORBIT', 4, '[0,1,2,3]'::jsonb);
INSERT INTO public.codenames_curated_puzzles (words, assignment, first_clue, first_clue_number, first_clue_target_indices) VALUES ('["KNIFE","NEEDLE","PIN","SPIKE","FILE","DRILL","NAIL","BOLT","NUT","STICK","STRING","NET","WEB","LINK","PLATE","GLASS","PAPER","BOARD","BOX","BLOCK","BUTTON","BELL","BOOT","BOTTLE","BOMB"]'::jsonb, '["blue","blue","blue","blue","blue","blue","blue","blue","blue","red","red","red","red","red","red","red","red","neutral","neutral","neutral","neutral","neutral","neutral","neutral","assassin"]'::jsonb, 'SHARP', 2, '[0,1]'::jsonb);
